exec: &exec
  name: build-tools/nerves-system-br
  version: 1.16.3
  elixir: 1.12.2-otp-24

version: 2.1

orbs:
  build-tools: nerves-project/build-tools@0.1.4

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build-tools/build-system:
          exec:
            <<: *exec
          context: nerves-build
          filters:
            tags:
              only: /.*/
      - build-tools/deploy-system:
          exec:
            <<: *exec
          context: nerves-build
          requires:
            - build-tools/build-system
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
